<?php

/***************************************************
 * form入力画面
 *
 *
 * @package
 * @access  public
 * @author  
 * @create  
 * @version 
 ***************************************************/

require_once('common/base_model_front_base.inc');

class form_input extends base_model_front_base {

//
//public function initialize() {  }
//public function finalize() {  }

//処理
public function execute() {

}

} // end of class

